spring:
  datasource:
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false

springdoc:
  default-produces-media-type: application/json
  api-docs:
    path: /docs/api
  swagger-ui:
    tags-sorter: alpha
    path: /docs/api/ui

auto:
  queue:
    delay: 5000
    interval: 10000
  mirror-path: ${AUTO_MIRRORS_PATH:/home/mkotz/mirrors}
  docker-repo: ci.kolektiv.dev
